name: Steve Herman
favicon: null
layout_spectrum: 0.18604292534291744
typography_spectrum: 0.3282855881843716
title: steve-herman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e6fa9'
    - '#6bc4c8'
    - '#060608'
    - '#2d4642'
    - '#d6eadd'
  brandStrength: 0.6875
  lightness: 0.5505676788743585
  saturation: 0.9808352896943688
  rhythmicContrast: 0.25
purpose: []
