name: Steve Herman
favicon: null
layout_spectrum: 0.47698
typography_spectrum: 0.3282855881843716
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e6fa9'
    - '#6bc4c8'
    - '#060608'
    - '#2d4642'
    - '#d6eadd'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
