name: Steve Herman
favicon: null
layout_spectrum: 0.18604292534291744
typography_spectrum: 0.3282855881843716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8960937801748514
  lightness: 0.5505676788743585
  saturation: 0.9808352896943688
  rhythmicContrast: 0.6058122892864048
purpose: []
